//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sacEntities : DbContext
    {
        public sacEntities()
            : base("name=sacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAbonnementVerlenging> tblAbonnementVerlenging { get; set; }
        public virtual DbSet<tblChatMessages> tblChatMessages { get; set; }
        public virtual DbSet<tblChatRequests> tblChatRequests { get; set; }
        public virtual DbSet<tblChatroom> tblChatroom { get; set; }
        public virtual DbSet<tblDownloadState> tblDownloadState { get; set; }
        public virtual DbSet<tblEvents> tblEvents { get; set; }
        public virtual DbSet<tblGebruikers> tblGebruikers { get; set; }
        public virtual DbSet<tblGebruikersLiveTick> tblGebruikersLiveTick { get; set; }
        public virtual DbSet<tblGroepen> tblGroepen { get; set; }
        public virtual DbSet<tblSpotnetDownload> tblSpotnetDownload { get; set; }
        public virtual DbSet<tblUpdateFiles> tblUpdateFiles { get; set; }
        public virtual DbSet<tblUpdateInnerVersion> tblUpdateInnerVersion { get; set; }
        public virtual DbSet<tblDatabaseDownload> tblDatabaseDownload { get; set; }
        public virtual DbSet<tblIpData> tblIpData { get; set; }
        public virtual DbSet<tblMessages> tblMessages { get; set; }
        public virtual DbSet<tblSabState> tblSabState { get; set; }
        public virtual DbSet<tblSpotnet> tblSpotnet { get; set; }
    }
}
