//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDownloadState
    {
        public int Id { get; set; }
        public int GebruikersId { get; set; }
        public int GroepId { get; set; }
        public string EventTime { get; set; }
        public string State { get; set; }
        public int DownloadId { get; set; }
    }
}
