//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroepen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGroepen()
        {
            this.tblGebruikers = new HashSet<tblGebruikers>();
        }
    
        public int Id { get; set; }
        public string ServerURI { get; set; }
        public string ServerUsername { get; set; }
        public string ServerPassword { get; set; }
        public string GroepNaam { get; set; }
        public int GroepBeheerderID { get; set; }
        public string GroepExpires { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGebruikers> tblGebruikers { get; set; }
    }
}
