//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGebruikers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblGebruikers()
        {
            this.tblAbonnementVerlenging = new HashSet<tblAbonnementVerlenging>();
        }
    
        public int Id { get; set; }
        public string Gebruikersnaam { get; set; }
        public string HardwareID { get; set; }
        public string LaatstAangemeld { get; set; }
        public string Blocked { get; set; }
        public string BlockedReason { get; set; }
        public string AccountExpires { get; set; }
        public int IsAdmin { get; set; }
        public int GroepID { get; set; }
        public int Activated { get; set; }
        public string Emailadres { get; set; }
        public string Web_Wachtwoord { get; set; }
        public byte[] GebruikerImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAbonnementVerlenging> tblAbonnementVerlenging { get; set; }
        public virtual tblGroepen tblGroepen { get; set; }
    }
}
