//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIpData
    {
        public int GebruikerId { get; set; }
        public int GroepId { get; set; }
        public string IpAddress { get; set; }
        public string TimeStamp { get; set; }
    }
}
