//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessages
    {
        public int Id { get; set; }
        public int SendID { get; set; }
        public int ReceiveID { get; set; }
        public string Message { get; set; }
        public System.DateTime Tijdstip { get; set; }
    }
}
